import { Supplier, RegionWind, Typology, Profile, GlassOption } from "./types";

export const BRAZIL_REGIONS: RegionWind[] = [
  { name: "Região I (Sul/Sudeste)", v0: 45 },
  { name: "Região II (Centro-Oeste)", v0: 40 },
  { name: "Região III (Nordeste)", v0: 35 },
  { name: "Região IV (Norte)", v0: 30 },
  { name: "Região V (Extremo Sul)", v0: 50 },
];

export const SUPPLIERS: Supplier[] = [
  { id: "sup-01", name: "Alcoa / Hydro" },
  { id: "sup-02", name: "CBA" },
  { id: "sup-03", name: "Alumasa" },
  { id: "sup-04", name: "Perfileve" },
  { id: "sup-05", name: "Perfil Alumínio" },
];

export const TYPOLOGIES: Typology[] = [
  {
    id: "jan-correr",
    name: "Janela de Correr",
    category: "janela",
    defaultSlsRatio: 175,
    maxDeflectionLimit: 15,
  },
  {
    id: "jan-max",
    name: "Janela Maxim-ar",
    category: "janela",
    defaultSlsRatio: 175,
    maxDeflectionLimit: 15,
  },
  {
    id: "por-correr",
    name: "Porta de Correr",
    category: "porta",
    defaultSlsRatio: 175,
    maxDeflectionLimit: 20,
  },
  {
    id: "por-giro",
    name: "Porta de Giro",
    category: "porta",
    defaultSlsRatio: 175,
    maxDeflectionLimit: 20,
  },
  {
    id: "gc-torre",
    name: "Guarda-corpo Torre",
    category: "guarda-corpo",
    defaultSlsRatio: 175,
    maxDeflectionLimit: 10,
  },
  {
    id: "gc-perfil",
    name: "Guarda-corpo Perfil Contínuo",
    category: "guarda-corpo",
    defaultSlsRatio: 175,
    maxDeflectionLimit: 10,
  },
  {
    id: "pv-stick",
    name: "Pele de Vidro Stick",
    category: "pele-de-vidro",
    defaultSlsRatio: 250,
    maxDeflectionLimit: 20,
  },
  {
    id: "pv-unit",
    name: "Pele de Vidro Unitizada",
    category: "pele-de-vidro",
    defaultSlsRatio: 250,
    maxDeflectionLimit: 20,
  },
];

export const CATALOG: Profile[] = [
  // Perfil Alumínio
  {
    code: "PA-100",
    series: "Linha 25",
    supplierId: "sup-05",
    weight: 0.75,
    ix: 10.2,
    wx: 3.5,
    categories: ["janela", "porta"],
  },
  {
    code: "PA-200",
    series: "Linha 30",
    supplierId: "sup-05",
    weight: 1.05,
    ix: 16.8,
    wx: 5.8,
    categories: ["janela", "porta"],
  },
  {
    code: "PA-300",
    series: "Linha 42",
    supplierId: "sup-05",
    weight: 1.65,
    ix: 35.4,
    wx: 12.2,
    categories: ["janela", "porta", "pele-de-vidro"],
  },
  {
    code: "PA-GC1",
    series: "Guarda-Corpo",
    supplierId: "sup-05",
    weight: 2.1,
    ix: 45.0,
    wx: 15.5,
    categories: ["guarda-corpo"],
  },
  // Hydro
  {
    code: "SU-200",
    series: "Suprema",
    supplierId: "sup-01",
    weight: 0.85,
    ix: 12.5,
    wx: 4.2,
    categories: ["janela", "porta"],
  },
  {
    code: "SU-201",
    series: "Suprema",
    supplierId: "sup-01",
    weight: 1.1,
    ix: 18.2,
    wx: 6.1,
    categories: ["janela", "porta"],
  },
  {
    code: "SU-202",
    series: "Suprema",
    supplierId: "sup-01",
    weight: 1.45,
    ix: 25.4,
    wx: 8.5,
    categories: ["janela", "porta"],
  },
  {
    code: "MA-300",
    series: "Master",
    supplierId: "sup-01",
    weight: 1.2,
    ix: 22.0,
    wx: 7.5,
    categories: ["janela", "porta"],
  },
  {
    code: "MA-301",
    series: "Master",
    supplierId: "sup-01",
    weight: 1.65,
    ix: 35.5,
    wx: 12.0,
    categories: ["janela", "porta"],
  },
  {
    code: "CG-001",
    series: "CG",
    supplierId: "sup-01",
    weight: 2.5,
    ix: 50.0,
    wx: 15.0,
    categories: ["guarda-corpo"],
  },
  {
    code: "PV-100",
    series: "Ecovida",
    supplierId: "sup-01",
    weight: 3.2,
    ix: 120.0,
    wx: 35.0,
    categories: ["pele-de-vidro"],
  },
  {
    code: "PV-101",
    series: "Ecovida",
    supplierId: "sup-01",
    weight: 4.5,
    ix: 180.0,
    wx: 50.0,
    categories: ["pele-de-vidro"],
  },
  // CBA
  {
    code: "CB-25",
    series: "Linha 25",
    supplierId: "sup-02",
    weight: 0.9,
    ix: 14.0,
    wx: 4.8,
    categories: ["janela", "porta"],
  },
  {
    code: "CB-30",
    series: "Linha 30",
    supplierId: "sup-02",
    weight: 1.3,
    ix: 24.0,
    wx: 8.0,
    categories: ["janela", "porta"],
  },
  {
    code: "CB-42",
    series: "Linha 42",
    supplierId: "sup-02",
    weight: 1.8,
    ix: 40.0,
    wx: 14.0,
    categories: ["janela", "porta"],
  },
  {
    code: "CB-GC",
    series: "Linha GC",
    supplierId: "sup-02",
    weight: 2.8,
    ix: 55.0,
    wx: 18.0,
    categories: ["guarda-corpo"],
  },
  {
    code: "CB-PV",
    series: "Linha PV",
    supplierId: "sup-02",
    weight: 3.5,
    ix: 130.0,
    wx: 40.0,
    categories: ["pele-de-vidro"],
  },
];

export const GLASS_CATALOG: GlassOption[] = [
  { id: "g-4-m", thickness: 4, type: "monolithic", admissibleStress: 15 },
  { id: "g-6-m", thickness: 6, type: "monolithic", admissibleStress: 15 },
  { id: "g-8-m", thickness: 8, type: "monolithic", admissibleStress: 15 },
  { id: "g-10-m", thickness: 10, type: "monolithic", admissibleStress: 15 },
  { id: "g-6-t", thickness: 6, type: "tempered", admissibleStress: 40 },
  { id: "g-8-t", thickness: 8, type: "tempered", admissibleStress: 40 },
  { id: "g-10-t", thickness: 10, type: "tempered", admissibleStress: 40 },
  { id: "g-12-t", thickness: 12, type: "tempered", admissibleStress: 40 },
  { id: "g-6-l", thickness: 6, type: "laminated", admissibleStress: 15 },
  { id: "g-8-l", thickness: 8, type: "laminated", admissibleStress: 15 },
  { id: "g-10-l", thickness: 10, type: "laminated", admissibleStress: 15 },
  { id: "g-12-l", thickness: 12, type: "laminated", admissibleStress: 15 },
  { id: "g-16-l", thickness: 16, type: "laminated", admissibleStress: 15 },
  { id: "g-20-l", thickness: 20, type: "laminated", admissibleStress: 15 },
];
